spring:
  datasource:
     url: jdbc:mysql://192.168.88.128:3306/test_db?useUnicode=true&characterEncoding=utf-8
     username: root
     password: 123456
     driver-class-name: com.mysql.jdbc.Driver