server:
  port: 9992

eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:9991/eureka/,http://peer3:9993/eureka/
  server:
    renewalPercentThreshold: 0.49